### PR TITLE
Feature/playv 893

### PR DESCRIPTION
**Pull request by bclabs-kate**
# Link for the issue
Fixes # (issue) https://bclabs.atlassian.net/browse/PLAYV-893

# What
-  Card hover, active 효과 추가

### CODE REVIEW

**Review by bclabs-paul — DISMISSED** [review]
XD

**Review by bclabs-theo — DISMISSED** [review]
Good

**Review by bclabs-mia — APPROVED** [review]

**Review by bclabs-paul — APPROVED** [review]
🏆🏆🏆🏆🏆

**Review by bclabs-theo — APPROVED** [review]
go!

**Pull request merged**
